package org.cdms.remoting.exception;

import java.util.ArrayList;
import java.util.List;
import org.cdms.remoting.validation.RemoteConstraintViolation;

/**
 * The class may be used to notify remote clients of the validation exceptions 
 * raised on a remote server. 
 * Suppose the remote client is a pure swing applications that knows
 * nothing of <code>Spring | Hibernate | JPA</code>. The application
 * communicates with a remote Spring-based server through Hessian
 * (or any other) RMI protocol. When the client 
 * invokes a remote method then an exceptions may occur on the server.
 * The server application translates the validation exception and transfers 
 * to the client an object of type <code>RemoteValidationException</code>
 * instead of the <i>native</i> one. This allows server side application 
 * to use different validation frameworks or API.
 * The class allows an exception that is thrown on the server side
 * be send back to the client independently of the used remote protocol.
 * The class corresponds the server side validation exception that is generated by
 * the server side application.
 * 
 * @author Valery
 */
public class RemoteValidationException extends RuntimeException {
    
    private List<RemoteConstraintViolation> violations;
    /**
     * Create a new instance of the class with a given message.
     * The constructor creates an empty list of the objects of type
     * {@link org.cdms.remoting.validation.RemoteConstraintViolation }
     * @param message the text to be displayed
     */
    public RemoteValidationException(String message) {
        super(message);
        violations = new ArrayList<RemoteConstraintViolation>();
    }
    
    public RemoteValidationException(String message,Object invalidValue,String constraintMessage,
            String constraintMessageTemplate, String propertyPath) {
        this(message);
    }
    /**
     * @return the list of the objects of type 
     * {@link org.cdms.remoting.validation.RemoteConstraintViolation }
     */
    public List<RemoteConstraintViolation> getViolations() {
        return violations;
    }

    
}
